baseURL = 'https://tjappen.com/'
locale = 'en-us'
title = 'tjappen.'

[taxonomies]
  cuisine = "cuisines"
  course = "courses"
  effort = "efforts"
  diet = "diets"

[outputs]
  home = ["HTML", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
